export const enum DateFormats {
  DDMMYYYY = 'DDMMYYYY',
  'DD-MMM-YYYY' = 'DD-MMM-YYYY',
  'h:mm a' = 'h:mm a',
  'DD-MM-YYYY' = 'DD-MM-YYYY',
  'DD/MM/YYYY' = 'DD/MM/YYYY',
  'MM/DD/YYYY' = 'MM/DD/YYYY',
  YYYYMMDD = 'YYYYMMDD',
  'YYYY-MM-DD' = 'YYYY-MM-DD',
  'YYYY/MM/DD' = 'YYYY/MM/DD',
  'YYYY-MM-DDTHH:mm:ss' = 'YYYY-MM-DDTHH:mm:ss',
  'YYYY-MM-DDTHH:mm:ss.SSSZ' = 'YYYY-MM-DDTHH:mm:ss.SSSZ',
  'DD-MM' = 'DD-MM',
  'dayjs' = 'dayjs',
  'date' = 'date',
  'YYYYMMDDHHmmssSSS' = 'YYYYMMDDHHmmssSSS',
  'YYYY-MM-DD-HH.mm.ss.SSSSSS' = 'YYYY-MM-DD-HH.mm.ss.SSSSSS',
  'ISO-String' = 'YYYY-MM-DDTHH:mm:ss.SSS[Z]',
}
